### ISSUE TITLE
Account dropdown no longer works in nav bar

### ISSUE THREAD

**Issue by styloooo** [timthejiang/grade-grabber#1]
Also, when the navbar is collapsed, the button expands the navbar, but it will not close the navbar.

**Comment by thirawr** [comment]
Also, when the navbar is collapsed, the button expands the navbar, but it will not close the navbar.

**Comment by timthejiang** [comment]
5dce379bcdaf2ffdd8df3d730ef8423ef8059de5

**Comment by timthejiang** [comment]
Fixed: 5dce379bcdaf2ffdd8df3d730ef8423ef8059de5
